### ISSUE TITLE
Crash on unchecked attributes 

### ISSUE THREAD

**Issue by Helco** [christianliebel/dhbw-webeng2-demo-api#1]
The server crashes on empty POST requests, as request attributes are not checked.

```
xxxxxxxxxxxxx\dhbw-webeng2-demo-api\controllers\todo.controller.js:18
        const todo = new Todo(todoId++, req.body.name, req.body.done);
                                                 ^

TypeError: Cannot read property 'name' of undefined
    at server.post (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\controllers\todo.c
ontroller.js:18:50)
    at call (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\node_modules\restify\lib\
chain.js:164:9)
    at next (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\node_modules\restify\lib\
chain.js:120:9)
    at Chain.run (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\node_modules\restify
\lib\chain.js:123:5)
    at onRoute (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\node_modules\restify\l
ib\routerRegistryRadix.js:46:25)
    at afterUse (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\node_modules\restify\
lib\server.js:920:9)
    at Server._afterUse (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng2-demo-api\node_modules\
restify\lib\server.js:1012:5)
    at Immediate.useChainDone [as _onImmediate] (C:\Users\D067826\Documents\Studium\Web2\dhbw-webeng
2-demo-api\node_modules\restify\lib\server.js:979:14)
    at runCallback (timers.js:795:20)
    at tryOnImmediate (timers.js:751:5)
```

**Comment by christianliebel** [comment]
Hi @Helco! Thanks for letting me know. If you like, please prepare a pull request which fixes this issue. I’d be more than happy to merge it! Thank you.
